### ISSUE TITLE
[FR] Add Titles to Trait Links

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/ttrpg-convert-cli#167]
## Scope

Trait Links

## Description

Adding `"title"` to the markdown trait links would allow me to successfully style multiple links and have automatic colors assigned to them. Implementing this would help me close the final issue on #114.

Adding a title also allows for increased specificity in the form of a `[href=]` in addition to a `[title=]` if needed.

#### Rarity
Common `Common Rarity`
Uncommon `Uncommon Rarity`
Rare `Rare Rarity`
Unique `Unique Rarity`

CSS I would add for this:
  ```scss
  &[title="Uncommon Rarity"] {
    background: rgb(152, 81, 61);
    background-clip: padding-box;
    border: 0.3rem solid rgb(152, 81, 61);

    @include link-styles;
  }
  ```

And another for every rarity item. 

#### Alignments

Alignments, I suggest ending the title with `alignment`.

LG `LG Alignment`
CN `CN Alignment`

CSS I would add for this:
```scss
  &[title*="Alignment"] {
    background: rgb(102, 111, 153);
    background-clip: padding-box;
    border: 0.3rem solid rgb(102, 111, 153);

    @include link-styles;
  }
```

#### Sizes

Sizing, I suggest ending the title with `sizing`.

Small `Small Sizing`
Large `Large Sizing`

CSS I would add for this:
```scss
  &[title*="Sizing"] {
    background: rgb(82, 122, 95);
    background-clip: padding-box;
    border: 0.3rem solid rgb(82, 122, 95);

    @include link-styles;
  }
```

#### Traits

For traits, I suggest ending the title with `traits`.

CSS I would add for this:

Dragon `Dragon Traits`
Primal `Primal Traits`
Elemental `Elemental Traits`

```scss
  &[title*="Traits"] {
    background: rgb(97, 20, 5);
    background-clip: padding-box;
    border: 0.3rem solid rgb(97, 20, 5);

    @include link-styles;
  }
```

### Other

This is the mixin for link-styles:

```scss
@mixin link-styles {
  border-radius: 5px;
  color: rgb(232, 232, 232) !important;
  cursor: help;
  font-weight: 700;
  margin-bottom: 0.75rem;
  padding: 0.1rem;
  text-align: center;
  text-indent: 0;
  word-break: keep-all;
  font-style: normal;
  display: inline-block;
}
```
