### ISSUE TITLE
🐛 InvalidPathException for external images

### ISSUE THREAD

**Issue by digitalnoiz** [ebullient/ttrpg-convert-cli#335]
When parsing homebrew content with external image urls, an error is occurring:
```
[ ? ERR] build(): Error processing 'Abyssal Hyena': java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/_img/FleeMortals/token/Abyssal Hyena.png
[ ? ERR] An error occurred: Illegal char <:> at index 5: https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/_img/FleeMortals/token/Abyssal Hyena.png.
```

example config.yaml:
```yaml
---
full-source:
  homebrew:
  - D:\dev\_vtt\homebrew\creature\MCDM Productions; Flee, Mortals!.json
paths:
  compendium: compendium/
  rules: compendium/rules/
```

## Configuration

- **OS**: Windows 11
- **CLI version**: 
    ttrpg-convert version 299-SNAPSHOT
    Git commit: 3b7420a
    Build time: 2024-02-11T13:53:52-0600 
- **CLI type**: jar
`java -jar .\ttrpg-convert-cli-299-SNAPSHOT-runner.jar -c .\config.yaml -o hbtst  D:\dev\_vtt\5etools\data`
**Sources**:
- enabled sources
  - none
- custom templates (attach if possible) 
  - none
